apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause-deployment
spec:
  selector:
    matchLabels:
      app: pause
  replicas: 8 
  template:
    metadata:
      labels:
        app: pause
    spec:
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.1
      topologySpreadConstraints:
      - maxSkew: 3
        topologyKey:  zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: pause
      - maxSkew: 2
        topologyKey:  rack
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: pause
      - maxSkew: 2
        topologyKey:  hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: pause
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key:  zone
                operator: In
                values:
                - cn-wh-02
