apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause-deployment
spec:
  selector:
    matchLabels:
      app: pause
  replicas: 7 
  template:
    metadata:
      labels:
        app: pause
    spec:
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.1
      topologySpreadConstraints:
      - maxSkew: 2
        topologyKey:  zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: pause
      - maxSkew: 1
        topologyKey:  rack
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
           matchLabels:
            app: pause
      - maxSkew: 1
        topologyKey:  hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
           matchLabels:
            app: pause
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: 
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pause
            topologyKey:  hostname
